### ISSUE TITLE
Undefined variable `escape`

### ISSUE THREAD

**Issue by XhmikosR** [yoksel/url-encoder#15]
https://github.com/yoksel/url-encoder/blob/dadb691197fff6165f310c33d935ed9c8b244734/script.js#L143

**Comment by yoksel** [comment]
Where did you get this error?

**Comment by XhmikosR** [comment]
It's clear it's not defined by looking at the code. But you can set up a
litter to catch such errors automatically.

**Comment by yoksel** [comment]
It's native JS function, it's just works, I don't get any errors in browsers. Do you get error in browser?

Anyway I just changed `encode` to `encodeURIComponent`.
